routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Route::prefix('admin')->name('admin.')->namespace('Admin')->middleware(['auth'])->group(function() {
    Route::resource('empresas', 'EmpresasController');
    Route::resource('funcionarios', 'FuncionariosController');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Empresa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    protected $table = 'empresas';
    protected $fillable = [
        'nome',
        'email',
        'website',
        'logo'
    ];

    protected $dates = [
      'created_at',
      'updated_at',
      'deleted_at',
    ];
    protected $hidden = [
      'deleted_at'
    ];

    public function funcionarios()
    {
        return $this->hasMany(Funcionario::class, 'empresa_id');
    }
}

app/Models/Funcionario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    protected $table = 'funcionarios';
    protected $primaryKey = 'cpf';
    protected $keyType = 'string';
    protected $fillable = [
        'cpf',
        'empresa_id',
        'nome',
        'telefone',
        'email'
    ];
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    protected $hidden = [
        'deleted_at'
    ];


    public function empresas()
    {
        return $this->belongsTo(Empresa::class, 'empresa_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    public function index()
    {
        return view('admin.home');
    }
}

app/Http/Controllers/Admin/EmpresasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Empresas\Store;
use App\Http\Requests\Empresas\Update;
use App\Models\Empresa;
use App\Repositories\ImageRepository;
use App\Http\Controllers\Controller;

class EmpresasController extends Controller
{
    protected $imageRepository;

    public function __construct(ImageRepository $imageRepository)
    {
        $this->imageRepository = $imageRepository;
    }

    public function index()
    {
        $empresas = Empresa::paginate(10);

        return view('admin.empresas.index', compact('empresas'));
    }

    public function create()
    {
        return view('admin.empresas.create');
    }

    public function store(Store $request)
    {
        try {
            $empresa = Empresa::create($request->only('nome', 'email', 'website'));
            $empresa->logo = $this->imageRepository->saveImage($request->file('logo'), $empresa->id);

            $empresa->save();
        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.empresas.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.empresas.index')
            ->with('success', 'Empresa inserida com sucesso.');
    }

    public function edit(Empresa $empresa) {
        return view('admin.empresas.edit', compact('empresa'));
    }

    public function update(Update $request, Empresa $empresa) {
        try {

            $empresa->update($request->only('nome', 'email', 'website'));

            if ($request->file('logo')) {
                $this->imageRepository->deleteImage($empresa->logo, $empresa->id);
                $empresa->logo = $this->imageRepository->saveImage($request->file('logo'), $empresa->id);
            }

            $empresa->save();
        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.empresas.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.empresas.index')
            ->with('success', 'Empresa atualizada com sucesso');
    }

    public function destroy(Empresa $empresa) {
        try {
            $empresa->delete();
            $this->imageRepository->deleteImage($empresa->logo, $empresa->id);
        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.empresas.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.empresas.index')
            ->with('success', 'Empresa excluída com sucesso!');
    }
}

app/Http/Controllers/Admin/FuncionariosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Funcionarios\Store;
use App\Http\Requests\Funcionarios\Update;
use App\Models\Empresa;
use App\Models\Funcionario;
use App\Http\Controllers\Controller;

class FuncionariosController extends Controller
{
    public function index()
    {
        $funcionarios = Funcionario::with('empresas')->paginate(10);

        return view('admin.funcionarios.index', compact('funcionarios'));
    }

    public function create()
    {
        $empresas = Empresa::all();
        return view('admin.funcionarios.create')->with('empresas', $empresas);
    }

    public function store(Store $request)
    {
        try {
            Funcionario::create($request->validated());

        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.funcionarios.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.funcionarios.index')
            ->with('success', 'Funcionário inserido com sucesso.');
    }

    public function edit(Funcionario $funcionario)
    {
        $empresas = Empresa::all();
        return view('admin.funcionarios.edit', compact('funcionario'))->with('empresas', $empresas);
    }

    public function update(Update $request, Funcionario $funcionario) {
        try {

            $funcionario->update($request->validated());

        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.funcionarios.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.funcionarios.index')
            ->with('success', 'Funcionário atualizado com sucesso');
    }

    public function destroy(Funcionario $funcionario) {
        try {
            $funcionario->delete();
        } catch (\Exception | \Throwable $e) {
            return redirect()->route('admin.funcionarios.index')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.funcionarios.index')
            ->with('success', 'Funcionário excluído com sucesso!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/empresas/create.blade.php
@extends('admin.layout')
@include('admin.request-error')


<div class="container">
    <div class="col-md-12">
        <div class="form-area">
            <form role="form" action="{{ route('admin.empresas.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Adicionar Empresa</h3>
                <div class="form-group">
                    <label for="nome">Name:</label><br>
                    <input type="text" class="form-control"  id="nome" name="nome" placeholder="nome" required value="{{old('nome')}}">
                </div>
                <div class="form-group">
                    <label for="email">E-mail:</label><br>
                    <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{old('email')}}">
                </div>
                <div class="form-group">
                    <label for="url">Web site:</label><br>
                    <input type="url" class="form-control" id="website" name="website" placeholder="Web Site" value="{{old('website')}}">
                </div>
                <div class="form-group">
                    <label for="logo">Logo:</label><br>
                    <input type="file" class="form-control" name="logo" id="logo">
                </div>
                <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Enviar</button>
                <button type="button" id="voltar" name="voltar" onclick="window.location.href='{{ route('admin.empresas.index') }}'" class="btn btn-info pull-left">Voltar</button>

            </form>
        </div>
    </div>
</div>

resources/views/admin/empresas/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.request-error')
    <div class="container">
        <div class="col-md-12">
            <div class="form-area">
                <form role="form" action="{{ route('admin.empresas.update', $empresa->getKey()) }}" method="POST" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Editar Empresa</h3>
                    <div class="form-group">
                        <label for="nome">Name:</label><br>
                        <input type="text" class="form-control"  id="nome" name="nome" placeholder="nome" required value="{{$empresa->nome}}">
                    </div>
                    <div class="form-group">
                        <label for="email">E-mail:</label><br>
                        <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{$empresa->email}}">
                    </div>
                    <div class="form-group">
                        <label for="url">Web site:</label><br>
                        <input type="url" class="form-control" id="website" name="website" placeholder="Web Site" value="{{$empresa->website}}">
                    </div>
                    <div class="form-group">
                        <label for="logo">Logo:</label><br>
                        <input type="file" class="form-control" name="logo" id="logo">
                    </div>
                    <div class="form-group" style="width: 100px">
                        <image src="{{ @asset('storage/' . $empresa->logo) }}" class="img-thumbnail card-img" style="width: auto;"/>
                    </div>
                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Enviar</button>
                    <button type="button" id="voltar" name="voltar" onclick="window.location.href='{{ route('admin.empresas.index') }}'" class="btn btn-info pull-left">Voltar</button>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/empresas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <br style="clear:both">
            <div class="col-lg-12">
                <div class="float-lg-left">
                    <h2>Listar Empresas</h2>
                </div>
                <div class="float-lg-right">
                    <a class="btn btn-success" href="{{ route('admin.empresas.create') }}"> Inserir</a>
                </div>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped table-condensed">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>E-mails</th>
                    <th>Web Site</th>
                    <th width="280px">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($empresas as $empresa)
                    <tr>
                        <td style="width: 75px;">
                            <image src="{{ @asset('storage/' . $empresa->logo) }}" class="img-thumbnail card-img" style="width: auto;"/>
                        </td>
                        <td>{{ $empresa->id }}</td>
                        <td>{{ $empresa->nome }}</td>
                        <td>{{ $empresa->email }}</td>
                        <td>{{ $empresa->website }}</td>
                        <td>
                            <form action="{{ route('admin.empresas.destroy',$empresa->id) }}" method="POST">
                                <a class="btn btn-primary" href="{{ route('admin.empresas.edit',$empresa->id) }}">Editar</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" onclick="javascript: return confirm('Deseja realamente exluir?');">Excluir</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {!! $empresas->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/funcionarios/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.request-error')
    <div class="container">
        <div class="col-md-12">
            <div class="form-area">
                <form role="form" action="{{ route('admin.funcionarios.store') }}" method="POST">
                    @csrf
                    <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Adicionar Funcionário</h3>
                    <div class="form-group">
                        <label for="empresa_id">Empresa:</label><br>
                        <select class="form-control"  id="empresa_id" name="empresa_id">
                            <option value="">Selecione</option>
                            @foreach($empresas as $empresa)
                                <option value="{{$empresa->id}}">{{$empresa->nome}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF:</label><br>
                        <input type="text" class="form-control"  id="cpf" name="cpf" placeholder="CPF"  value="{{old('cpf')}}">
                    </div>
                    <div class="form-group">
                        <label for="Nome">Nome:</label><br>
                        <input type="text" class="form-control"  id="nome" name="nome" placeholder="Nome" value="{{old('nome')}}">
                    </div>
                    <div class="form-group">
                        <label for="email">E-mail:</label><br>
                        <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{old('email')}}">
                    </div>
                    <div class="form-group">
                        <label for="url">Telefone:</label><br>
                        <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Web Site" value="{{old('telefone')}}">
                    </div>
                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Enviar</button>
                    <button type="button" id="voltar" name="voltar" onclick="window.location.href='{{ route('admin.funcionarios.index') }}'" class="btn btn-info pull-left">Voltar</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/funcionarios/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.request-error')
    <div class="container">
        <div class="col-md-12">
            <div class="form-area">
                <form role="form" action="{{ route('admin.funcionarios.update', $funcionario->getKey()) }}" method="POST">
                    @method('PATCH')
                    @csrf
                    <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Editar Funcionário</h3>
                    <div class="form-group">
                        <label for="empresa_id">Empresa:</label><br>
                        <select class="form-control"  id="empresa_id" name="empresa_id">
                            <option value="">Selecione</option>
                            @foreach($empresas as $empresa)
                                <option value="{{$empresa->id}}" {{ $funcionario->empresa_id == $empresa->id?'selected':'' }}>{{$empresa->nome}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF:</label><br>
                        <input type="text" class="form-control"  id="cpf" name="cpf" placeholder="CPF"  value="{{ $funcionario->cpf }}">
                    </div>
                    <div class="form-group">
                        <label for="Nome">Nome:</label><br>
                        <input type="text" class="form-control"  id="nome" name="nome" placeholder="Nome" value="{{ $funcionario->nome }}">
                    </div>
                    <div class="form-group">
                        <label for="email">E-mail:</label><br>
                        <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{  $funcionario->email }}">
                    </div>
                    <div class="form-group">
                        <label for="url">Telefone:</label><br>
                        <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Web Site" value="{{  $funcionario->telefone }}">
                    </div>
                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Enviar</button>
                    <button type="button" id="voltar" name="voltar" onclick="window.location.href='{{ route('admin.funcionarios.index') }}'" class="btn btn-info pull-left">Voltar</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/funcionarios/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <br style="clear:both">
            <div class="col-lg-12">
                <div class="float-lg-left">
                    <h2>Listar Funcionários</h2>
                </div>
                <div class="float-lg-right">
                    <a class="btn btn-success" href="{{ route('admin.funcionarios.create') }}"> Inserir</a>
                </div>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped table-condensed">
                <thead>
                <tr>
                    <th>CPF</th>
                    <th>Nome</th>
                    <th>E-mails</th>
                    <th>Telefone</th>
                    <th>Empresa</th>
                    <th width="280px">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($funcionarios as $funcionario)
                    <tr>
                        <td>{{ $funcionario->cpf }}</td>
                        <td>{{ $funcionario->nome }}</td>
                        <td>{{ $funcionario->email }}</td>
                        <td>{{ $funcionario->telefone }}</td>
                        <td>{{ $funcionario->empresas->nome }}</td>
                        <td>
                            <form action="{{ route('admin.funcionarios.destroy', $funcionario->cpf) }}" method="POST">
                                <a class="btn btn-primary" href="{{ route('admin.funcionarios.edit', (string) $funcionario->getKey()) }}">Editar</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" onclick="javascript: return confirm('Deseja realamente exluir?');">Excluir</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {!! $funcionarios->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('admin.layout')

resources/views/admin/request-error.blade.php
@if (!empty($errors->all()))
    <br style="clear:both">
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>

    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
        .form-area
        {
            background-color: #FAFAFA;
            padding: 10px 40px 60px;
            margin: 10px 0px 60px;
            border: 1px solid GREY;
        }
        .logo {
            display: inline-block;
            vertical-align: middle;
            height: 40px;
            margin: 5px 30px 0 0;

        }
    </style>
    <link href="{{asset('admin/css/menu.css')}}" rel="stylesheet" id="menu-css">
    <script>
        $(document).ready(function(){
            $('.top-line').after('<div class="mobile-menu d-xl-none">');
            $('.top-menu').clone().appendTo('.mobile-menu');
            $('.mobile-menu-btn').click(function(){
                $('.mobile-menu').stop().slideToggle();
            });
        });
    </script>
</head>
<body>
<div id="app">
    <header class="top-line">
        <img class="logo" src="http://controlaltweb.com.br/site/img/logo2-bco-header.png" alt="logo alt">
        <div class="phone"><i class="fa fa-phone"></i>(16) 3443-2244 </div>
        <div class="mobile-menu-btn"><i class="fa fa-bars"></i> Меню</div>
        <nav class="main-menu top-menu">
            <ul>
                @guest
                    <li>
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li>
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="active"><a href="/home">Home</a></li>
                    <li><a href="{{route('admin.empresas.index')}}">Empresas</a></li>
                    <li><a href="{{route('admin.funcionarios.index')}}">Funcionários</a></li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endguest
            </ul>
        </nav>
    </header>
    <div class="container">
        <br style="clear:both">
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @elseif($message = Session::get('error'))
            <div class="alert alert-danger">
                <p>{{ $message }}</p>
            </div>
        @endif
    </div>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>